export type Lang = 'en' | 'zh';

const strings = {
  en: {
    title: 'Startup',
    deck: 'Evidence-backed startup company reports generated by specialized research agents.',
    reports: 'Reports',
    search: 'Search',
    archive: 'All dossiers',
    sectors: 'Sectors',
    topRated: 'Top rated',
    latest: 'Latest',
    noReports: 'No reports yet.',
    confidence: 'confidence',
    market: 'Market',
    financials: 'Financials',
    risks: 'Top risks',
  },
  zh: {
    title: '创业公司研究',
    deck: '由专业研究 Agent 生成的、基于证据的创业公司深度报告。',
    reports: '报告',
    search: '搜索',
    archive: '全部报告',
    sectors: '赛道',
    topRated: '高分报告',
    latest: '最新',
    noReports: '暂无报告。',
    confidence: '置信度',
    market: '市场',
    financials: '财务',
    risks: '主要风险',
  },
} as const;

export function t(key: keyof typeof strings.en, lang: Lang = 'en'): string {
  return strings[lang][key] ?? strings.en[key];
}
