const strings = {
  en: {
    title: 'Startup',
    deck: 'Evidence-backed startup company reports generated by specialized research agents.',
    reports: 'Reports',
    search: 'Search',
    archive: 'All dossiers',
    sectors: 'Sectors',
    topRated: 'Top rated',
    latest: 'Latest',
    noReports: 'No reports yet.',
    confidence: 'confidence',
    market: 'Market',
    financials: 'Financials',
    risks: 'Top risks',
  },
} as const;

export function t(key: keyof typeof strings.en): string {
  return strings.en[key];
}
